# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/amadeusk525/Documents/Amadeus/Amadeus-Writer/sdk/wxShapeFramework/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/FindwxWidgets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/UsewxWidgets.cmake))

/Users/amadeusk525/Documents/Amadeus/Amadeus-Writer/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.24.0/bin/cmake -H/Users/amadeusk525/Documents/Amadeus/Amadeus-Writer -B/Users/amadeusk525/Documents/Amadeus/Amadeus-Writer
